# Generated by Django 4.0.3 on 2022-04-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='recipeUrl',
            field=models.TextField(null=True),
        ),
    ]
